# Generated by Django 6.0.3 on 2026-03-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=1000, unique=True)),
                ('name_ru', models.CharField(max_length=1000, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
